language: node_js
node_js:
- '6'
- '10'
jobs:
  include:
  - stage: deploy
    script: skip
    node_js:
    - '10'
    deploy:
      skip_cleanup: true
      provider: npm
      email: qm3ster@gmail.com
      api_key:
        secure: nLt7kfU0lpjt1Pr6bPIZnhubnwjWU6YzNUhP5shWp3YGNUjBm2srB0+GX0qVoAEgjAu9mbz/943CDu9idTB8RH3Lp2HgXZ62ZoZbl5yHVNU6sM0mYCETiTixof/vfhKW2hyUnt1Ylvz2J4OyP0Q8fK3fPXouDsQkCNgL4qGDZh+VtQutqlVtiD0SxDkera3x5HxZ99Kq0k/bkhdJVrxvi0eC3a+NWKsTt9uSAa/fQuFJE2FZMzm6KOh5j2/188Beihw/hk0W7x3CDvGgTzlQCQGXyyxQY6NbhxU1XXQjfRedKGiCf9L77PntSAcPPCP+9t+T+yGGMV8aLy3xvNbaicDU5ElQm/Eaz0y54B9dB2SAPCpPJAcaMRMH+0xyky3005OniiHvTcf4lrzfb98eXQLheoN8klWX+nZ7FtzBNDZborF1mlYDJbOhNnqtlPC5qmRcnBGFwx7/LZrZfeJRi/UcASsFbVkPridClEIIMx8orIVJRhS49B9ncVGwoY+acGX1BR3BcorbH/tzXBM9Wglv6XtgNK+NCt/AB+mllo8TdgIJbX2vEdwXHBRtC9XGbGkvbmeNr9e1svs7/6wVBk+W7+8TE73KgDcajxTwdzIcEt3g9toN1A5RKvRawtbCBBsliFLWsw0NxZB7eDLU3it41DVF6YNvp7JNnSKenPM=
      on:
        tags: true
        repo: ZigBeans/zcl-id
